/*package test;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Testing {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
	/*
	 * driver = new ChromeDriver(); js = (JavascriptExecutor) driver; vars = new
	 * HashMap<String, Object>();
	 */
 /*WebDriverManager.chromedriver().setup();
 driver= new ChromeDriver ();
 driver.manage().window().maximize();
 
}
@After
public void tearDown() {
 //driver.quit();
}
@Test
public void flip() {
 driver.get("https://www.flipkart.com/");
 driver.manage().window().setSize(new Dimension(1280, 690));
 driver.findElement(By.cssSelector(".\\_2doB4z")).click();
 {
   WebElement element = driver.findElement(By.linkText("Become a Seller"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 driver.findElement(By.name("q")).click();
 driver.findElement(By.name("q")).sendKeys("watch");
 driver.findElement(By.cssSelector(".\\_34RNph:nth-child(2)")).click();
 {
   WebElement element = driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(2) > .\\_13oc-S:nth-child(1) > div:nth-child(1) .\\_2r_T1I:nth-child(1)"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
}
}*/
